development:
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


# development:
#   secret_key_base: 9e655562f8bf8c6f86fb3e7b04abc2689f93b889b41a0dacbaff1e98e5e3069e2c5f2e643834e98f36ab5e08d74a13ceabbff79b34133499aae669be52070e6c

# test:
#   secret_key_base: 1b84bff9dab578d59b591d012bb0f846d89bc96a51d046dad161802db881347f20369533e7b708e20d7d31c9cf67828b4ecd173b65e2d518116b710366f6ef64

# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
